name: AUR Publish 🐧

on:
  push:
    tags:
      - "*"

jobs:
  aur-publish:
    name: Publish package to Arch User Repository (AUR)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2
        with:
          pkgname: nodejs-knit
          pkgbuild: ./PKGBUILD
          # update checksum(s)
          updpkgsums: true
          # verify build succeeds
          test: true
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "feature(release,aur): publish AUR package"
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
