name: Release 🏗️

on:
  workflow_run:
    workflows: ["Test 🧪"]
    types: [completed]
    branches: [master]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Handle release 🦋
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: yarn
      - name: Create release PR or publish package
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          title: "feature(release): version packages"
          commit: "ci(changesets): version packages"
        env:
          # custom PAT used due to https://github.com/changesets/action/issues/187
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
